spring.application.name=MyThreeDimensionalLand

spring.datasource.url=jdbc:sqlite:data/app.db?foreign_keys=on&journal_mode=WAL
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always